name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, Linux, lab, austin]
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build
      shell: bash
      run: |
        dotnet --info
        set -e
        pwsh -file release.ps1 Release
    - name: Test
      shell: pwsh
      run: dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration Release --no-build /p:AltCover=true /p:AltCoverStrongNameKey=../../SharpSnmpLib/sharpsnmplib.snk /p:AltCoverAssemblyFilter='^(xunit)|(AltCover)|(SharpSnmpLib\.Tests)'
